# Generated by Django 5.2.14 on 2026-06-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=99, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('profile_pic', models.FileField(blank=True, upload_to='user/')),
            ],
        ),
    ]
