# Generated by Django 5.2.14 on 2026-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_desk_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietitian',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('qualification', models.TextField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('registration_no', models.CharField(max_length=30)),
                ('profile_pic', models.FileField(blank=True, upload_to='dietitian/')),
            ],
        ),
    ]
