# Generated by Django 5.2.14 on 2026-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_desk_app', '0002_dietitian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=30)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
