# Generated by Django 5.2.14 on 2026-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_desk_app', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietitian_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('post', models.TextField()),
            ],
        ),
    ]
