# Generated by Django 5.2.14 on 2026-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_desk_app', '0004_dietitian_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsr_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField()),
                ('message', models.TextField()),
                ('phone', models.CharField()),
            ],
        ),
    ]
