# Generated by Django 5.2.14 on 2026-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_desk_app', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firsr_name',
            new_name='first_name',
        ),
    ]
